// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraceabilityAPI.Models;

#nullable disable

namespace TraceabilityAPI.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20221112043936_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TraceabilityAPI.Models.DetailTransportPtoP", b =>
                {
                    b.Property<string>("billId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("itemBillId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status_request")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("billId");

                    b.ToTable("DetailTransportPtoP");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.Factory", b =>
                {
                    b.Property<string>("factoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<string>("addressFactory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("factoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personInCharge")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("factoryId");

                    b.ToTable("Factory");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.FactoryRequest", b =>
                {
                    b.Property<string>("productId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("factoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status_request")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("productId");

                    b.ToTable("FactoryRequest");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.Farm", b =>
                {
                    b.Property<string>("farmId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<string>("addressFarm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("farmName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("farmerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("farmId");

                    b.ToTable("Farm");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.FarmRequest", b =>
                {
                    b.Property<string>("harvestId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("farmId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status_request")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("harvestId");

                    b.ToTable("FarmRequest");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.Fruit", b =>
                {
                    b.Property<string>("fruitId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_plant")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("farmId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fertilizer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fruitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("land")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pesticides")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("seedId")
                        .HasColumnType("int");

                    b.Property<string>("status_activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("technology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fruitId");

                    b.ToTable("Fruit");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.FruitHarvest", b =>
                {
                    b.Property<string>("harvestId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_harvest")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("fruitId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status_request")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("weight_harvest")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("harvestId");

                    b.ToTable("FruitHarvest");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.InventoryFactory", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("factoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("harvestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("InventoryFactory");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.InventoryStore", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("productId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("storeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("InventoryStore");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.Merchant", b =>
                {
                    b.Property<string>("merchantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<string>("addressMerchant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("merchantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("traderId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("merchantId");

                    b.ToTable("Merchant");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.MerchantFarm", b =>
                {
                    b.Property<string>("billId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("farmId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("harvestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("merchantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status_request")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("weight_mf")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("billId");

                    b.ToTable("MerchantFarm");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.Person", b =>
                {
                    b.Property<string>("identification")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<string>("addressPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("birthDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imagePerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("working")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("identification");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.Product", b =>
                {
                    b.Property<string>("productId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<int>("amountProduct")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("elementOfProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("exp_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("factoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("harvestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("humidity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("mfg_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("net_weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("procedureOfProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("temperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("typeProductId")
                        .HasColumnType("int");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("productId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.Seed", b =>
                {
                    b.Property<int>("seedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("seedId"), 1L, 1);

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("seedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("seedId");

                    b.ToTable("Seed");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.Store", b =>
                {
                    b.Property<string>("storeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<string>("addressStore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("storeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("storeId");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.Transport", b =>
                {
                    b.Property<string>("transportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<string>("addressTransport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personInCharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transportName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("transportId");

                    b.ToTable("Transport");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.TransportPtoP", b =>
                {
                    b.Property<string>("billId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("humidity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("placeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status_request")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("temperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("transportId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("billId");

                    b.ToTable("TransportPtoP");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.TypeProduct", b =>
                {
                    b.Property<int>("typeProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("typeProductId"), 1L, 1);

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("typeProductId");

                    b.ToTable("TypeProduct");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.UpToTransport", b =>
                {
                    b.Property<string>("billId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("goodsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status_request")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("billId");

                    b.ToTable("UpToTransport");
                });

            modelBuilder.Entity("TraceabilityAPI.Models.UserLogin", b =>
                {
                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("_role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_update")
                        .HasColumnType("datetime2");

                    b.Property<string>("pass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("represent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("workingFor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userName");

                    b.ToTable("UserLogin");
                });
#pragma warning restore 612, 618
        }
    }
}
