export interface DetailFull {
    id : string,
    productId : string,
    productName : string,
    factoryId : string,
    factoryName : string,
    factoryEmail : string,
    addressFactory : string,
    ifId : string,
    harvestId : string,
    date_harvest : string,
    mfg_date : string,
    exp_date : string,
    net_weight :number,
    procedureOfProduct : string,
    elementOfProduct : string,
    tfactory :number,
    hfactory :number,
    storeId : string,
    storeName : string,
    storePhone : string,
    storeEmail : string,
    addressStore : string,
    fruitId : string,
    fruitName : string,
    technology : string,
    land : string,
    fertilizer : string,
    pesticides : string,
    date_plant : string,
    farmId : string,
    farmName : string,
    addressFarm : string,
    billId1 : string,
    itemBill1 : string,
    placeId1 : string,
    transportId1 : string,
    transportName1 : string,
    emailTransport1 : string,
    addressTransport1 : string,
    tTransportUTO :number,
    hTransportUTO :number,
    placeUTO : string,
    goodsUTO : string,
    toPlaceUTO : string,
    billId2 : string,
    itemBill2 : string,
    placeId2 : string,
    transportId2 : string,
    transportName2 : string,
    emailTransport2 : string,
    addressTransport2 : string,
    tTransportMF :number,
    hTransportMF :number,
    placeMF : string,
    goodsMF : string,
    toPlaceMF : string,
    merchantId : string,
    merchantName : string,
    addressMerchant : string,
    imageProduct : string,
    imageQR : string,
    checkM : number,
    imageFH : string,
}