export interface DetailLiveWTM {
    id: string,
    harvestId: string,
    date_harvest: string,
    storeId: string,
    storeName: string,
    storePhone: string,
    storeEmail: string,
    addressStore: string,
    fruitId: string,
    fruitName: string,
    technology: string,
    land: string,
    fertilizer: string,
    pesticides: string,
    date_plant: string,
    farmId: string,
    farmName: string,
    addressFarm: string,
    billId: string,
    itemBill: string,
    placeId: string,
    transportId: string,
    transportName: string,
    emailTransport: string,
    addressTransport: string,
    tTransportUTO : number,
    hTransportUTO : number,
    placeUTO : string,
    goodsUTO : string,
    toPlaceUTO : string,
    imageQR : string,
    imageFH : string,
}