export interface Notice {
    id : string, 
    sendId : string, 
    receiveId : string, 
    title : string, 
    content : string, 
    status_request : string, 
    sendDate : string, 
    receiveDate : string, 
    representSend : string, 
    roleSend : string, 
    workingForSend : string, 
    sendName : string, 
    photoSend : string, 
    representReiceive : string, 
    roleReceive : string, 
    workingForReceive : string, 
    receiveName : string, 
    photoReceive : string, 
}