export interface PSView {
    productId : string,
    productName : string,
    factoryId : string,
    factoryName : string,
    addressFactory : string,
    harvestId : string,
    amountProduct : number,
    typeProductId : number,
    mfg_date : string,
    exp_date : string,
    net_weight : number,
    unit : string,
    temperature : number,
    humidity : number,
    procedureOfProduct : string,
    elementOfProduct : string,
}